### ISSUE TITLE
Option to move re-exports to import from original module

### ISSUE THREAD

**Issue by anall** [oalders/App-perlimports#15]
I'm not sure how possible this is, but it would be nice for there to be an option to rewrite includes of re-exported symbols to the original module.

For example:

```
# LegacyModule.pm
package LegacyModule;
use strict;
use base qw(Exporter);
use NewModule qw(moved_function);
our @EXPORT_OK = qw(moved_function);
1;

# NewModule.pm
package NewModule;
use strict;
use base qw(Exporter);
our @EXPORT_OK = qw(moved_function);
sub moved_function { return 42; }
1;

# test.pl
use strict;
use LegacyModule qw(moved_function);
print moved_function();
```

It would be nice if `perlimports` could suggest `use NewModule qw(moved_function);` instead, but I guess this would require recursively examining all required modules.

**Comment by oalders** [comment]
Excellent thought. My question here is how to know if this is the behaviour we'd want. We can already detect if something is just being re-exported, but sometimes that's what you want. Say, if you have a module that imports from `List::Util` and also `List::SomeUtils` and `List::UtilsBy` and it's just re-exporting for convenience.

In that case you wouldn't want to rewrite the imports with the module of origin since that now defeats the wrapper module you've created.

**Comment by anall** [comment]
In this case, we have a legacy module that had to be split in two at one point, and instead of finding every use of `moved_function` everything apparently just got re-exported and our codebase is a mess of both `use LegacyModule qw(moved_function);` and `use NewModule qw(moved_function);`

Possibly a command-line argument where we can list modules where this is desired?

**Comment by oalders** [comment]
I'll have to think about this. On the one hand, I might normally just use a find and replace to deal with this, but it might be helpful to make `perlimports` smart about deprecated modules, so that it could replace them automatically. That might make it even smarter than `goimports`. 😄

**Comment by anall** [comment]
Just a note: for my use-case as some things still belong in `LegacyModule` (the names I used in my example/redactions don't perfectly match our internal use-case) -- so the module isn't fully deprecated.

But I really do like the idea about being smart re. deprecated modules.

**Comment by oalders** [comment]
Thanks very much for raising this issue. I'm going to close it because I don't see a path to including this functionality in `perlimports` as it currently stands. I think what we probably need is a class of modules which can be smart about rewriting Perl code. @gugod is doing something very interesting with https://github.com/gugod/App-PerlNitpick which may actually be a much better fit for this particular use case.

**Comment by anall** [comment]
That's fine. This was really just a random thought as well as a "I wonder if this module has the data to make that work".
